---
title: "Functions"
output:
  workflowr::wflow_html:
    theme: flatly
    css: static/style.css
    toc: true
    code_folding: show
editor_options:
  chunk_output_type: console
---

All functions that used in this projects

+ [**CPLASS()**](functions.html#cplass)

+ [**CPLASS_paths()**](functions.html#cplass_paths)

+ [**plot_path_inferred()**](functions.html#plot_path_inferred)

+ [**plot_path_actual_and_inferred()**](functions.html#plot_path_actual_and_inferred)

+ [**plot_csa()**](functions.html#plot_csa)

## CPLASS

**Description**

This function runs the Continuous Piecewise Linear Approximation with Stochastic Search (CPLASS) algorithm on a 2D data in the form of $(x_i,y_i)_{i=1}^n$ observed at time $(t_i)_{i=1}^n$ believed to follow a continuous piecewise linear regression model (Gaussian noise). It is used for detecting changes in velocity problem. CPLASS returns the time changes, the estimated parameters.

**Usage**

```r
 CPLASS(t,x, y,time_rate, lambda_r=1/30, 
                  iter_max = 5000, burn_in=500, s_cap=1, 
                  gamma=1.01, speed_pen=TRUE, Diagnostic = FALSE, 
                  sd = NA, pen = "ssic") 
```

**Arguments**

| Argument     | Description |
|--------------|-------------|
| **x**        | A vector containing the data sequence (Cargo locations in x-axis) |
| **y**        | A vector containing the data sequence (Cargo locations in y-axis) |
| **t**        | A vector containing time |
| **time_rate**        | Time step, e.g., 0.001, 0.01, 0.04, 0.05, 0.1, 1 |
| **lambda_r** | the rate used in the proposal of a new vector of changepoints |
| **iter_max** | The maximum number of iterations for running Metropolis-Hastings searching algorithm |
| **burn_in**    | The number of burn-in steps in MH search algorithm|
| **s_cap**    | The threshold for the output speed. If the inferred speed exceed `s_cap` and the `speed_pen` is activated, then the extra speed penalty will be introduced|
| **gamma**      | The power in the strengthened Schwarz Information Criterion (sSIC) |
| **speed_pen**  | If `TRUE`, adding the speed penalty to the penalty function; if `FALSE`, we only use the linear penalty term sSIC |
| **Diagnostic**  | If `TRUE`, a dataframe with all of update in the stochastic search will be printed|
| **sd**  | The standard deviation value of the noise of the data. If it is unknown, then CPLASS will estimate it. |
| **pen**  | Either `aicc` or `ssic`. The options to choose the information criterion. `aicc` for the Corrected Akaike Information Criterion, `ssic` for the strengthened Schwarz Information Criterion. |

**Output**

A list of `segment_inferred` and `path_inferred` will be returned after running the algorithm. 

- The `segment_inferred` is a tibble containing 8 columns 

| Columns     | Description |
|--------------|-------------|
| **cp_times** | The inferred change times |
| **durations**| The inferred segment durations |
| **states**   | A binary vector labeling the state of the associated segments, `0` for stationary, `1` for motile. The labels are created using the cut-off method with a threshold of 100nm/s |
| **speeds**   | The inferred segment speeeds |
| **vx** | The inferred velocity with respect to x-axis |
| **vy** | The inferred velocity with respect to y-axis|

- The `path_inferred` is a tibble containing 6 columns

| Columns     | Description |
|--------------|-------------|
| **t** | The input time |
| **j**| The label of time points corresponding to the labels of segments after using the cut-off method |
| **x**   |The observed data with respect to x-axis  |
| **y**   | The observed data with respect to y-axis |
| **a** | The inferred piecewise linear lines (anchor locations w.r.t x-axis) |
| **b** | The inferred piecewise linear lines (anchor locations w.r.t y-axis)|

**Example** 

[← CPLASS Analysis](example_on_running-CPLASS.html#cplass)


## CPLASS_paths

For running CPLASS on a collection of paths, we introduced the function `CPLASS_paths`.

**Usage**

```r
CPLASS_paths(data, PARALLEL = FALSE, time_rate, 
                        lambda_r=1/30, iter_max = 5000, burn_in=500, 
                        s_cap=1, gamma=1.01, speed_pen=TRUE, sd = NA,
                        pen = "ssic")
```

**Arguments**

| Argument     | Description |
|--------------|-------------|
| **data**     | A list of paths where for each path we can specify $t,x,y$ |
| **time_rate**| Time step, e.g., 0.001, 0.01, 0.04, 0.05, 0.1, 1 |
| **PARALLEL** | If `TRUE`, running parallel computing; if `FALSE`, running sequentially
| **lambda_r** | the rate used in the proposal of a new vector of changepoints |
| **iter_max** | The maximum number of iterations for running Metropolis-Hastings searching algorithm |
| **burn_in**    | The number of burn-in steps in MH search algorithm|
| **s_cap**    | The threshold for the output speed. If the inferred speed exceed `s_cap` and the `speed_pen` is activated, then the extra speed penalty will be introduced|
| **gamma**      | The power in the strengthened Schwarz Information Criterion (sSIC) |
| **speed_pen**  | If `TRUE`, adding the speed penalty to the penalty function; if `FALSE`, we only use the linear penalty term sSIC |
| **sd**  | The standard deviation value of the noise of the data. If it is unknown, then CPLASS will estimate it. |
| **pen**  | Either `aicc` or `ssic`. The options to choose the information criterion. `aicc` for the Corrected Akaike Information Criterion, `ssic` for the strengthened Schwarz Information Criterion. |


**Output**

A list of paths, in each path, there is a similar output with two sublists `segments_inferred` and `path_inferred` as described in the `CPLASS` function.

**Warnings**

At the moment, we do not encourage using `CPLASS_paths` unless you provide the correct format of the data so that `CPLASS_paths` can read it. We are working on updating this function so that it is more user-friendly in the near future. To run CPLASS with a list of paths, please click here [← CPLASS Analysis](example_on_running-CPLASS.html#cplass_paths).





## plot_path_inferred

**Description**

This function return a plot for a segmented path after running CPLASS.

**Usage**

```r 
plot_path_inferred(path_info,xy_width = NA,t_lim = NA, motor, max_speed, state_shaded = TRUE, title_ind = NA, show_time_changes = FALSE)
```

**Arguments**

| Argument     | Description |
|--------------|-------------|
| **path_info**| A list of segmented trajectory. The trajectory must contain the two sublists including `path_inferred` and `segment_inferred` information as `CPLASS` output. |
| **xy_width**        | Adjust the frame size of the plot |
| **t_lim**        | The limit of `t` in the plot |
| **motor**        | Title of the plot, e.g., `motor = "Kinesin"`  |
| **lambda_r** | The rate used in the proposal of a new vector of changepoints |
| **max_speed** | The maximum speed among all collection of inferred segment speeds after running CPLASS |
| **state_shaded**    | `TRUE` for showing the color of the motile/stationary segments|
| **title_ind**    |`TRUE` for showing index of paths, e.g., `path 1`, `path 2`|
| **show_time_changes**      | `TRUE` for showing the change times in the plot with dashed lines |

**Output**

A plot with four panels showing the xy plot, x-vs-t, y-vs-t, and a plot on segment durations/segment speeds.

**Example** 

[← Visualization examples](visualization_tools.html#plot_path_inferred)



## plot_path_actual_and_inferred

**Description**

This function return a plot for a simulated trajectory where we can compare the actual vs inferred trajectories.

**Usage**

```r 
plot_path_actual_and_inferred(path_info, xy_width = NA, t_lim = NA, state_shaded = TRUE)
```

**Arguments**

| Argument     | Description |
|--------------|-------------|
| **path_info**| A list of segmented trajectory. The trajectory must contain the two sublists including `path_inferred` and `segment_inferred` information as `CPLASS` output. |
| **xy_width**        | Adjust the frame size of the plot |
| **t_lim**        | The limit of `t` in the plot |
| **motor**        | Title of the plot, e.g., `motor = "Kinesin"`  |
| **state_shaded**    | `TRUE` for showing the color of the motile/stationary segments|

**Output**

A plot with four panels showing the xy plot, x-vs-t, y-vs-t, and a plot on segment durations/segment speeds.

**Example** 

[← Visualization examples](visualization_tools.html#plot_path_actual_and_inferred)




## plot_csa

**Description**

This function return a plot for a simulated trajectory where we can compare the actual vs inferred trajectories.

**Usage**

```r 
plot_csa(csa, legend = TRUE)
```

**Arguments**

| Argument     | Description |
|--------------|-------------|
| **csa**| A data frame that include calculated CSAs |
| **legend**        | `TRUE` show the legend of the plot |

**Output**

CSA plot

**Example** 

[← Visualization examples](visualization_tools.html#plot_csa)



